### ISSUE TITLE
RadSecproxy isn't installing 

### ISSUE THREAD

**Issue by fsilveira060** [Khosmos/EasyLifeNetworks#14]

**Comment by AnaSilverio** [comment]
Could you be more specific about the details during the process of install ?

—
Reply to this email directly or view it on GitHub
https://github.com/Khosmos/EasyLifeNetworks/issues/14.

**Comment by fsilveira060** [comment]
In the variables file, all parameters for this process are commented.

**Comment by CosmeFC** [comment]
Inside variables.sh you can see some instructions. There is no variables for RadSecproxy, only instructions. You must use the zip file fom RNP before start. It is not easy test this module.
