### ISSUE TITLE
Erros na instalação

### ISSUE THREAD

**Issue by sergiogambarra** [Khosmos/EasyLifeNetworks#17]
CENTOS 7

ERRO 1:
[root@wifi tmp]# git clone https://github.com/Khosmos/EasyLifeNetworks.git
Cloning into 'EasyLifeNetworks'...
remote: Counting objects: 1186, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 1186 (delta 0), reused 0 (delta 0), pack-reused 1176
Receiving objects: 100% (1186/1186), 8.06 MiB | 653.00 KiB/s, done.
Resolving deltas: 100% (495/495), done.
[root@wifi tmp]# cd EasyLifeNetworks/
[root@wifi EasyLifeNetworks]# . ./installeln.sh 
/usr/share/EasyLifeNetworks/confs/variables.sh: line 9: lsb_release: comando não encontrado
/usr/share/EasyLifeNetworks/confs/variables.sh: line 11: lsb_release: comando não encontrado
/usr/share/EasyLifeNetworks/confs/variables.sh: line 108: sipcalc: comando não encontrado
/usr/share/EasyLifeNetworks/lib/common/isgoodos.sh: line 13: [: =: esperado operador unário
./eln.sh: line 23: return: can only `return' from a function or sourced script
Plugins carregados: fastestmirror, langpacks
base                                                     | 3.6 kB     00:00  
extras                                                   | 3.4 kB     00:00  
updates                                                  | 3.4 kB     00:00  
Loading mirror speeds from cached hostfile
- base: centos.ufes.br
- extras: centos.ufes.br
- updates: centos.ufes.br
  Resolvendo dependências
  --> Executando verificação da transação
  ---> O pacote epel-release.noarch 0:7-5 será instalado
  --> Resolução de dependências finalizada

Dependências resolvidas

ERRO 2

![erro1](https://cloud.githubusercontent.com/assets/7014291/11097407/6886813a-8886-11e5-83b1-04c390bfa47a.png)

ERRO 3

Após alterar o arquivo variaveis e salvar aparece o erro abaixo:

/usr/share/EasyLifeNetworks/confs/variables.sh: line 108: sipcalc: comando não encontrado
Variables module finished
Press <Enter> to exit

**Comment by CosmeFC** [comment]
Fixed
