### ISSUE TITLE
chown: não é possível acessar “/etc/init.d/monitorix”

### ISSUE THREAD

**Issue by sergiogambarra** [Khosmos/EasyLifeNetworks#19]
Monitorix

...
Concluído!
Setup Monitorix
chown: não é possível acessar “/etc/init.d/monitorix”: Arquivo ou diretório não encontrado
Nota: Encaminhando requisição para 'systemctl enable monitorix.service'.
ln -s '/usr/lib/systemd/system/monitorix.service' '/etc/systemd/system/multi-user.target.wants/monitorix.service'
Redirecting to /bin/systemctl restart  monitorix.service
Redirecting to /bin/systemctl restart  httpd.service
Monitorix module finished

**Comment by CosmeFC** [comment]
Fix fixed.
