### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by sergiogambarra** [Khosmos/EasyLifeNetworks#22]
...
esgotado para conexão
Tentando novamente.

--2015-11-12 20:01:00--  ftp://mirror.switch.ch/pool/4/mirror/fedora/linux/releases/22/Everything/x86_64/os/Packages/f/fwbuilder-5.1.0.3599-5.fc20.x86_64.rpm
  (tentativa:20) => “fwbuilder-5.1.0.3599-5.fc20.x86_64.rpm”
Conectando-se a mirror.switch.ch (mirror.switch.ch)|2001:620:0:8::20|:21... conectado.
Acessando como anonymous ... Acesso autorizado!
==> SYST ... feito.   ==> PWD ... feito.
==> TYPE I ... feito. ==> CWD (1) /pool/4/mirror/fedora/linux/releases/22/Everything/x86_64/os/Packages/f ... feito.
==> SIZE fwbuilder-5.1.0.3599-5.fc20.x86_64.rpm ... 7003668
==> EPSV ... não foi possível se conectar a 2001:620:0:8::20 porta 56401: Tempo esgotado para conexão
Desistindo.

Plugins carregados: fastestmirror, langpacks
Não foi possível abrir: fwbuilder-5.1.0.3599*.rpm. Ignorando.
Nada a ser feito
erro ao ler informação sobre o serviço iptables: Arquivo ou diretório não encontrado
erro ao ler informação sobre o serviço ip6tables: Arquivo ou diretório não encontrado

Firewall module finished

You must:
- choose your firewall in /root/FirewallTemplates/
- save as /root/firewall.fwb
- study, modify and compile
- copy firewall.fw to /etc/init.d/
- restart firewall
  - service firewall restart

**Comment by CosmeFC** [comment]
Fixed
