### ISSUE TITLE
bash: modules.sh: Arquivo ou diretório não encontrado

### ISSUE THREAD

**Issue by sergiogambarra** [Khosmos/EasyLifeNetworks#23]
Após executar git clone, entrar na pasta cd EasyLifeNetworks e executar o  . ./installeln.sh, ele instala tudo e corrige todas as dependências, mas quando abre o menu onde devo selecionar entre PROFILES ou MODULES, ao deixar marcado o MODULES  e pressionar Enter ele sai do menu e não abre os MODULES.

Segue abaixo a parte final ao pressionar enter no OK.

---

Instalar  1 Package

Tamanho total do download: 14 k
Tamanho depois de instalado: 24 k
Downloading packages:
epel-release-7-5.noarch.rpm                                |  14 kB   00:00  
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Instalando   : epel-release-7-5.noarch                                    1/1 
  Verifying    : epel-release-7-5.noarch                                    1/1 

Instalados:
  epel-release.noarch 0:7-5                                                     

Concluído!
bash: modules.sh: Arquivo ou diretório não encontrado
[root@wifi bin]#

**Comment by CosmeFC** [comment]
Fixed
