### ISSUE TITLE
NX 

### ISSUE THREAD

**Issue by AnaSilverio** [Khosmos/EasyLifeNetworks#7]
- test for the implementation of nx centos7 - **DONE**
-  teste [nx](https://github.com/Khosmos/EasyLifeNetworks/blob/master/modules/NX.sh) in centos6

**Comment by AnaSilverio** [comment]
#### Installation test on centos 6.6

###### Installation test 1

![nxinstal1](https://cloud.githubusercontent.com/assets/13190644/10472001/2f5415de-71d0-11e5-9837-06385f9cb7d3.png)

###### Installation test 1 completed

![nxinstall1 1](https://cloud.githubusercontent.com/assets/13190644/10472057/d69c27e6-71d0-11e5-9236-997475e25440.png)

###### Installation test 2

![nxinstall2](https://cloud.githubusercontent.com/assets/13190644/10472061/dcc1be4c-71d0-11e5-8fcf-332d1a7a260f.png)

**Comment by AnaSilverio** [comment]
#### Test of NX using X2go on Centos 6.6

###### Tested with a VM using a ssh conecction in localhost

![nx func](https://cloud.githubusercontent.com/assets/13190644/10639735/7d04fcaa-77f0-11e5-9a39-7162600fe44d.png)
![nx funcionando](https://cloud.githubusercontent.com/assets/13190644/10639740/859956cc-77f0-11e5-836b-6ba7f5c5646b.png)

Worked on my machine.

**Comment by CosmeFC** [comment]
ok, it's working
